default:
  controller: Main
  action: home
  level_auth: 0

a-propos:
  controller: Main
  action: aboutUs
  level_auth: 0

about-us:
  controller: Main
  action: aboutUs
  level_auth: 0

contact:
  controller: Main
  action: contact
  level_auth: 0

login:
  controller: Auth
  action: login
  level_auth: 0

logout:
  controller: Auth
  action: logout
  level_auth: 1

s-inscrire:
  controller: Auth
  action: register
  level_auth: 0

view-type:
  controller: Type
  action: viewType
  level_auth: 0

add-type:
  controller: Type
  action: addType
  level_auth: 0

update-type:
  controller: Type
  action: updateType
  level_auth: 0

delete-type:
  controller: Type
  action: deleteType
  level_auth: 0
